/* auto-generated by napi-rs */
/* eslint-disable */

/** Options for rolling dice. */
export interface Options {
  /** Whether to show detailed roll results. Default: true. */
  showDetail?: boolean
  /** Optional random seed for deterministic results (testing). */
  seed?: number
}

/** The result of a roll operation. */
export interface RollResult {
  /** The source text that was successfully consumed. */
  consumed: string
  /** The remaining unparsed text (tail). */
  tail: string
  /** The summary string (final result without detail), e.g. "14" or "{10, 11, 13}". */
  summary: string
  /** The detail string (roll details), e.g. "[5 + 3 + 1* + 6]". */
  detail: string
  /** The full output combining detail and summary, e.g. "[5 + 3 + 1* + 6] = 14". */
  full: string
  /** Whether this is a multi-result set. */
  isSet: boolean
  /** The numeric values of the result. */
  values: number[]
}

/** The result of parsing (without rolling). */
export interface ParseOutput {
  /** Whether parsing succeeded. */
  success: boolean
  /** The source text that was successfully consumed. */
  consumed: string
  /** The remaining unparsed text (tail). */
  tail: string
}

/**
 * Parse and evaluate a dicelet expression.
 *
 * This function combines parsing and evaluation into one step.
 * It uses strtol-style fault-tolerant parsing: if the input contains
 * invalid syntax, it parses as much as possible and returns the
 * unparsed remainder as the `tail`.
 *
 * @example
 * ```typescript
 * const result = roll("4d6k3");
 * console.log(result.full); // e.g. "[5 + 3 + 1* + 6] = 14"
 * ```
 */
export function roll(expression: string, options?: Options): RollResult

/**
 * Parse a dicelet expression without rolling.
 *
 * Returns the consumed portion and the remaining tail.
 * Uses strtol-style fault-tolerant parsing.
 *
 * @example
 * ```typescript
 * const result = parse("d20 + (d4+ 测试");
 * console.log(result.success); // true
 * console.log(result.consumed); // "d20"
 * console.log(result.tail); // "+ (d4+ 测试"
 * ```
 */
export function parse(expression: string): ParseOutput