// Auto-generated by napi-rs
// Please do not edit manually

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd 2>/dev/null || true').toString().trim()
      if (lddPath) {
        const output = require('child_process').execSync(`${lddPath} --version 2>&1 || true`).toString()
        return output.includes('musl')
      }
    } catch (e) {
      // Ignore
    }
    return false
  }
  // Node 12+
  const { header } = process.report.getReport().header
  return header.glibcVersionRuntime == null
}

function requireNative() {
  switch (platform) {
    case 'android':
      switch (arch) {
        case 'arm64':
          try {
            return require('./dicelet.android-arm64.node')
          } catch (e) {
            loadError = e
          }
          break
        case 'arm':
          try {
            return require('./dicelet.android-arm-eabi.node')
          } catch (e) {
            loadError = e
          }
          break
        default:
          throw new Error(`Unsupported architecture on Android ${arch}`)
      }
      break
    case 'win32':
      switch (arch) {
        case 'x64':
          try {
            return require('./dicelet.win32-x64-msvc.node')
          } catch (e) {
            loadError = e
          }
          break
        case 'ia32':
          try {
            return require('./dicelet.win32-ia32-msvc.node')
          } catch (e) {
            loadError = e
          }
          break
        case 'arm64':
          try {
            return require('./dicelet.win32-arm64-msvc.node')
          } catch (e) {
            loadError = e
          }
          break
        default:
          throw new Error(`Unsupported architecture on Windows ${arch}`)
      }
      break
    case 'darwin':
      switch (arch) {
        case 'x64':
          try {
            return require('./dicelet.darwin-x64.node')
          } catch (e) {
            loadError = e
          }
          break
        case 'arm64':
          try {
            return require('./dicelet.darwin-arm64.node')
          } catch (e) {
            loadError = e
          }
          break
        default:
          throw new Error(`Unsupported architecture on macOS ${arch}`)
      }
      break
    case 'freebsd':
      if (arch !== 'x64') {
        throw new Error(`Unsupported architecture on FreeBSD ${arch}`)
      }
      try {
        return require('./dicelet.freebsd-x64.node')
      } catch (e) {
        loadError = e
      }
      break
    case 'linux':
      switch (arch) {
        case 'x64':
          if (isMusl()) {
            try {
              return require('./dicelet.linux-x64-musl.node')
            } catch (e) {
              loadError = e
            }
          } else {
            try {
              return require('./dicelet.linux-x64-gnu.node')
            } catch (e) {
              loadError = e
            }
          }
          break
        case 'arm64':
          if (isMusl()) {
            try {
              return require('./dicelet.linux-arm64-musl.node')
            } catch (e) {
              loadError = e
            }
          } else {
            try {
              return require('./dicelet.linux-arm64-gnu.node')
            } catch (e) {
              loadError = e
            }
          }
          break
        case 'arm':
          try {
            return require('./dicelet.linux-arm-gnueabihf.node')
          } catch (e) {
            loadError = e
          }
          break
        default:
          throw new Error(`Unsupported architecture on Linux ${arch}`)
      }
      break
    default:
      throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
  }
}

nativeBinding = requireNative()

if (!nativeBinding || loadError) {
  throw new Error(
    `Failed to load native binding${
      loadError ? ': ' + loadError.message : ''
    }`,
  )
}

module.exports = nativeBinding
module.exports.roll = nativeBinding.roll
module.exports.parse = nativeBinding.parse